# Generated by Django 4.2.4 on 2023-08-06 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Front', '0002_playlist_user_data_my_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='users',
            field=models.ManyToManyField(related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='my_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Front.playlist'),
        ),
    ]
