# Generated by Django 4.2.4 on 2023-08-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0003_playlist_users_alter_user_data_my_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='my_playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Front.user_data'),
        ),
    ]
